# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: floatchat-api
#     environment:
#       DATABASE_URL: postgresql://postgres:oceandata2024@postgres:5432/floatchat
#       NODE_ENV: development
#       PORT: 5000
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./backend:/app
#       - ./Data:/app/Data
#       - /app/node_modules

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#       args:
#         VITE_API_URL: http://localhost:5000
#     container_name: floatchat-web
#     depends_on:
#       - backend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     environment:
#       VITE_API_URL: http://localhost:5000

#   postgres:
#     image: postgres:16-alpine
#     container_name: floatchat-db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: oceandata2024
#       POSTGRES_DB: floatchat
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
#     healthcheck: 
#       test: ["CMD-SHELL", "pg_isready -U postgres"] 
#       interval: 10s 
#       timeout: 5s 
#       retries: 5

# volumes:
#   postgres_data:

# nginx: 
#   image: nginx:alpine 
#   container_name: floatchat-proxy 
#   depends_on: 
#     - frontend 
#     - backend 
#   ports: 
#     - "80:80" 
#   volumes: 
#     - ./nginx.conf:/etc/nginx/nginx.conf
version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: floatchat-api
    environment:
      DATABASE_URL: postgresql://postgres:oceandata2024@postgres:5432/floatchat
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./Data:/app/Data
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    container_name: floatchat-web
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:5000

  postgres:
    image: postgres:16-alpine
    container_name: floatchat-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oceandata2024
      POSTGRES_DB: floatchat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
      interval: 10s 
      timeout: 5s 
      retries: 5

  nginx: 
    image: nginx:alpine 
    container_name: floatchat-proxy 
    depends_on: 
      - frontend 
      - backend 
    ports: 
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
